language: cpp
compiler:
  - gcc
  - clang

before_install:
  - if [[ $CXX == "g++" ]] ; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test ; fi
  - if [[ $CXX == "clang++" ]] ; then sudo add-apt-repository -y ppa:yak1ex/llvm ; fi
  - sudo apt-get update
  - if [[ $CXX == "clang++" ]] ; then sudo apt-get install clang-3.3 ; fi
  - if [[ $CXX == "g++" ]] ; then sudo apt-get install gcc-4.7 g++-4.7 ; fi
  - sudo apt-get install zlib1g-dev
  - wget http://jaist.dl.sourceforge.net/boost/boost_1_54_0.tar.bz2
  - tar -xf boost_1_54_0.tar.bz2
  - ( cd boost_1_54_0  && ./bootstrap.sh --prefix=/usr --with-libraries=date_time,filesystem,exception,log,locale,random,regex,program_options,system,thread && sudo ./b2 -j2 link=static install ) > /dev/null

before_script:
  - if [[ $CXX == "g++" ]] ; then export CXX='g++-4.7' ; export CC='gcc-4.7' ; fi
  - if [[ $CXX == "clang++" ]] ; then export CXX='clang++-3.3' ; export CC='clang-3.3' ; fi
  - cmake . -DDEBUG=1

script:
    - make
    - ./avhttp http://www.boost.org/LICENSE_1_0.txt
    - ./avhttp https://github.com/blog
    - ./avhttp https://github.com/avplayer/avplayer/archive/master.zip
    - cat ./multi_download.log

branches:
  only:
    - master
    - C++11
notifications:
  recipients:
    - microcaicai@gmail.com
    - jack.wgm@gmail.com
  email:
    on_success: change
    on_failure: always

